const initialBoard = {
  a1: { piece: "rook", pieceColor: "white", squareColor: "dark" },
  b1: { piece: "knight", pieceColor: "white", squareColor: "light" },
  c1: { piece: "bishop", pieceColor: "white", squareColor: "dark" },
  d1: { piece: "queen", pieceColor: "white", squareColor: "light" },
  e1: { piece: "king", pieceColor: "white", squareColor: "dark" },
  f1: { piece: "bishop", pieceColor: "white", squareColor: "light" },
  g1: { piece: "knight", pieceColor: "white", squareColor: "dark" },
  h1: { piece: "rook", pieceColor: "white", squareColor: "light" },

  a2: { piece: "pawn", pieceColor: "white", squareColor: "light" },
  b2: { piece: "pawn", pieceColor: "white", squareColor: "dark" },
  c2: { piece: "pawn", pieceColor: "white", squareColor: "light" },
  d2: { piece: "pawn", pieceColor: "white", squareColor: "dark" },
  e2: { piece: "pawn", pieceColor: "white", squareColor: "light" },
  f2: { piece: "pawn", pieceColor: "white", squareColor: "dark" },
  g2: { piece: "pawn", pieceColor: "white", squareColor: "light" },
  h2: { piece: "pawn", pieceColor: "white", squareColor: "dark" },

  a3: { piece: "", pieceColor: "", squareColor: "dark" },
  b3: { piece: "", pieceColor: "", squareColor: "light" },
  c3: { piece: "", pieceColor: "", squareColor: "dark" },
  d3: { piece: "", pieceColor: "", squareColor: "light" },
  e3: { piece: "", pieceColor: "", squareColor: "dark" },
  f3: { piece: "", pieceColor: "", squareColor: "light" },
  g3: { piece: "", pieceColor: "", squareColor: "dark" },
  h3: { piece: "", pieceColor: "", squareColor: "light" },

  a4: { piece: "", pieceColor: "", squareColor: "light" },
  b4: { piece: "", pieceColor: "", squareColor: "dark" },
  c4: { piece: "", pieceColor: "", squareColor: "light" },
  d4: { piece: "", pieceColor: "", squareColor: "dark" },
  e4: { piece: "", pieceColor: "", squareColor: "light" },
  f4: { piece: "", pieceColor: "", squareColor: "dark" },
  g4: { piece: "", pieceColor: "", squareColor: "light" },
  h4: { piece: "", pieceColor: "", squareColor: "dark" },

  a5: { piece: "", pieceColor: "", squareColor: "dark" },
  b5: { piece: "", pieceColor: "", squareColor: "light" },
  c5: { piece: "", pieceColor: "", squareColor: "dark" },
  d5: { piece: "", pieceColor: "", squareColor: "light" },
  e5: { piece: "", pieceColor: "", squareColor: "dark" },
  f5: { piece: "", pieceColor: "", squareColor: "light" },
  g5: { piece: "", pieceColor: "", squareColor: "dark" },
  h5: { piece: "", pieceColor: "", squareColor: "light" },

  a6: { piece: "", pieceColor: "", squareColor: "light" },
  b6: { piece: "", pieceColor: "", squareColor: "dark" },
  c6: { piece: "", pieceColor: "", squareColor: "light" },
  d6: { piece: "", pieceColor: "", squareColor: "dark" },
  e6: { piece: "", pieceColor: "", squareColor: "light" },
  f6: { piece: "", pieceColor: "", squareColor: "dark" },
  g6: { piece: "", pieceColor: "", squareColor: "light" },
  h6: { piece: "", pieceColor: "", squareColor: "dark" },

  a7: { piece: "pawn", pieceColor: "black", squareColor: "dark" },
  b7: { piece: "pawn", pieceColor: "black", squareColor: "light" },
  c7: { piece: "pawn", pieceColor: "black", squareColor: "dark" },
  d7: { piece: "pawn", pieceColor: "black", squareColor: "light" },
  e7: { piece: "pawn", pieceColor: "black", squareColor: "dark" },
  f7: { piece: "pawn", pieceColor: "black", squareColor: "light" },
  g7: { piece: "pawn", pieceColor: "black", squareColor: "dark" },
  h7: { piece: "pawn", pieceColor: "black", squareColor: "light" },

  a8: { piece: "rook", pieceColor: "black", squareColor: "light" },
  b8: { piece: "knight", pieceColor: "black", squareColor: "dark" },
  c8: { piece: "bishop", pieceColor: "black", squareColor: "light" },
  d8: { piece: "queen", pieceColor: "black", squareColor: "dark" },
  e8: { piece: "king", pieceColor: "black", squareColor: "light" },
  f8: { piece: "bishop", pieceColor: "black", squareColor: "dark" },
  g8: { piece: "knight", pieceColor: "black", squareColor: "light" },
  h8: { piece: "rook", pieceColor: "black", squareColor: "dark" },
};

export default initialBoard;
